import java.util.List;
import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        String output = "";     
        int firstPromotionSave = 0;
        int secondPromotionSave = 0;
        int originCost = 0;
        int finalCost = 0;
        ArrayList<String> saveNameList = new ArrayList<>();

        output += "============= Order details =============\n";
        for(String input : inputs){
            String[] splitString = input.split(" ");
            for(Item item : this.itemRepository.findAll()){
                if(item.getId().equals(splitString[0])){
                    output += input.replaceAll(splitString[0],item.getName()) + " = " + (int)(item.getPrice() * Integer.parseInt(splitString[2])) + " yuan\n";
                    originCost += item.getPrice() * Integer.parseInt(splitString[2]);
                }
                for(SalesPromotion salesPromotion : this.salesPromotionRepository.findAll()){
                    if(salesPromotion.getType().equals("50%_DISCOUNT_ON_SPECIFIED_ITEMS")){
                        for(String promotionId : salesPromotion.getRelatedItems()){
                            if((item.getId().equals(splitString[0]) && item.getId().equals(promotionId))){
                                secondPromotionSave += item.getPrice() * Integer.parseInt(splitString[2]) * 0.5;
                                saveNameList.add(item.getName());
                            }
                        }
                    }
                }
            }
        }
        if(originCost >= 30){firstPromotionSave = 6;}
        System.out.println(secondPromotionSave);
        System.out.println(originCost);


        if(firstPromotionSave != 0 || secondPromotionSave != 0){
            output += "-----------------------------------\n";
            output += "Promotion used:\n";
            String saveNameString = "";
            for (int i=0; i < saveNameList.size(); i++){
                saveNameString += (i == saveNameList.size()-1) ?  saveNameList.get(i) : saveNameList.get(i) + "，";
            }
            output += (firstPromotionSave >= secondPromotionSave) ?
                    "Reach 30 yuan，saving 6 yuan\n"
                    : "Half price for certain dishes ("+ saveNameString + ")，saving " + secondPromotionSave + " yuan\n";
        }
        finalCost = (firstPromotionSave >= secondPromotionSave) ? originCost - firstPromotionSave : originCost - secondPromotionSave;

        output += "-----------------------------------\n";
        output += "Total：" + finalCost + " yuan\n";
        output += "===================================";

        return output;
    

    }    }
